name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build. https://github.com/Ryoishin/userbot_docker/blob/master/Dockerfile ryoishin/userbot:ryoishin alpine:$(date +%s)
